# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [26]:
a = pd.Series([100,200,300,400])

Print a, and data type

In [28]:
print(a,type(a))

0    100
1    200
2    300
3    400
dtype: int64 <class 'pandas.Series'>

Using indexing access the element 300 from the series a.

In [29]:
print(a[2])

300

What are the values of index for series a?

In [ ]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [38]:
a.index = ['a','b','c','d']

Access the value in the series with index 'd'

In [40]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [42]:
print(a.sort_index())

a    100
b    200
c    300
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [44]:
b = pd.Series([800,450,100], index = ['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [53]:
a = pd.concat([a,b])
print(a)

a    100
b    200
c    300
d    400
e    800
f    450
g    100
e    800
f    450
g    100
dtype: int64

In [54]:
#print a again after appending b into it
print(a)

a    100
b    200
c    300
d    400
e    800
f    450
g    100
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [55]:
print(a.sort_index(ascending=False))

g    100
g    100
f    450
f    450
e    800
e    800
d    400
c    300
b    200
a    100
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [56]:
df = pd.DataFrame(a,columns=["Values"])
df

   Values
a     100
b     200
c     300
d     400
e     800
f     450
g     100
e     800
f     450
g     100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [57]:

print(df.shape)

(10, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [8]:
# yep its same as the series.

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [59]:
print(df.head())
print(df.tail())

   Values
a     100
b     200
c     300
d     400
e     800
   Values
f     450
g     100
e     800
f     450
g     100

Rename the column of the dataframe as 'points'

In [61]:
df.columns = ['points']
df

   points
a     100
b     200
c     300
d     400
e     800
f     450
g     100
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [63]:
#Create fruits array

fruits = pd.Series(np.random.choice(['orange','apple','mango'],size = 7))
print(fruits)

0     apple
1    orange
2    orange
3     apple
4     mango
5     mango
6     mango
dtype: str

In [68]:
#Create series fruits out of fruits array

# fruits =
fruits = pd.Series(fruits)
print(fruits)

0     apple
1    orange
2    orange
3     apple
4     mango
5     mango
6     mango
dtype: str

Change the index of fruits to the index of dataframe df

In [69]:
fruits.index = df.index
print(fruits.index)

ValueError: Length mismatch: Expected axis has 7 elements, new values have 10 elements

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [81]:
d1 = pd.DataFrame({
    'city' : ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ],
    'Temperature' : [15, 22, 20, 26,-2]
})

Print(d1)

In [82]:

print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [83]:
print(d1.shape)

(5, 2)

Set city = d1['city']

In [84]:
city = d1['city']

print city <br>
What is the type of city.

In [87]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: str
<class 'pandas.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [88]:
d2 = pd.DataFrame({
    'city' : ['Benglaru','Comibatore','Srirangam','Pondicherry'],
    'Temperature' : [24,35,36,39]
})

print the shape of this dataframe

In [89]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [91]:
d3 = pd.concat([d1,d2], ignore_index = True)
d3

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5     Benglaru           24
6   Comibatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [92]:
cold_cities = d3[d3['Temperature']>=20]
print(cold_cities)

          city  Temperature
1        Delhi           22
2       Kanpur           20
3      Chennai           26
5     Benglaru           24
6   Comibatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [93]:

hot_cities = d3[d3['Temperature']>=35]
print(hot_cities)

          city  Temperature
6   Comibatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [108]:
# write function here
def is_ut(x):
    if x in ['Chandigarh','Pondicherry','Delhi']:
        print(True)
    else:
        print(False)

d3['is_ut'] = d3['city'].apply(is_ut)
# def is_ut(x):
    
#     # write code below
    
# d3['is_ut'] =

True
True
False
False
False
False
False
False
True

In [110]:
# print d3
d3

          city  Temperature is_ut  Temperature_F
0   Chandigarh           15  None           59.0
1        Delhi           22  None           71.6
2       Kanpur           20  None           68.0
3      Chennai           26  None           78.8
4       Manali           -2  None           28.4
5     Benglaru           24  None           75.2
6   Comibatore           35  None           95.0
7    Srirangam           36  None           96.8
8  Pondicherry           39  None          102.2

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [111]:
# write function here
def c_to_f(x):
    return (x * 9/5) + 32

In [112]:
# check function c_to_f(10)
c_to_f(10)

50.0

In [113]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['Temperature_F']=d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature is_ut  Temperature_F
0   Chandigarh           15  None           59.0
1        Delhi           22  None           71.6
2       Kanpur           20  None           68.0
3      Chennai           26  None           78.8
4       Manali           -2  None           28.4
5     Benglaru           24  None           75.2
6   Comibatore           35  None           95.0
7    Srirangam           36  None           96.8
8  Pondicherry           39  None          102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [114]:
d3[d3['is_ut'] == True]

Empty DataFrame
Columns: [city, Temperature, is_ut, Temperature_F]
Index: []

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [122]:
d3[d3['Temperature_F'] > 90]

          city  Temperature is_ut  Temperature_F
6   Comibatore           35  None           95.0
7    Srirangam           36  None           96.8
8  Pondicherry           39  None          102.2

Select only the first three rows of the dataframe d1.

In [123]:
d3.head(3)

         city  Temperature is_ut  Temperature_F
0  Chandigarh           15  None           59.0
1       Delhi           22  None           71.6
2      Kanpur           20  None           68.0

Select all the rows and last two columns in the dataframe.

In [128]:
d3.iloc[:,-2:]

  is_ut  Temperature_F
0  None           59.0
1  None           71.6
2  None           68.0
3  None           78.8
4  None           28.4
5  None           75.2
6  None           95.0
7  None           96.8
8  None          102.2

## Groupby

In [130]:
# Create a dataframe using dictionary of your choice

# data = 
data = {
    'Food' : ['Fish','Chicken','Turkey','Shrimp'],
    'Likeness' : [3,9,8,6]
}
df = pd.DataFrame(data)
df

      Food  Likeness
0     Fish         3
1  Chicken         9
2   Turkey         8
3   Shrimp         6

In [134]:
# Use Groupby of single column with aggregate sum()
print(df.groupby('Food')['Likeness'].sum())

Food
Chicken    9
Fish       3
Shrimp     6
Turkey     8
Name: Likeness, dtype: int64

In [135]:
# Use Groupby of single column with aggregate count()
print(df.groupby('Food')['Likeness'].count())

Food
Chicken    1
Fish       1
Shrimp     1
Turkey     1
Name: Likeness, dtype: int64

In [144]:
# Use Groupby of single column with aggregate min() and max()
print(df.groupby('Food')['Likeness'].agg(['min','max']))

         min  max
Food
Chicken    9    9
Fish       3    3
Shrimp     6    6
Turkey     8    8

In [145]:
# Use Groupby of any 2 columns with aggregate mean()
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Sales', 'Sales'],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'F'],
    'Salary': [50000, 60000, 40000, 45000, 55000, 50000]
}

df = pd.DataFrame(data)

print(df.groupby(['Department', 'Gender'])['Salary'].mean())

Department  Gender
HR          F         45000.0
            M         40000.0
IT          F         60000.0
            M         50000.0
Sales       F         50000.0
            M         55000.0
Name: Salary, dtype: float64

In [146]:
# Use Groupby of any 2 columns with aggregate min() and max()

print(df.groupby(['Department', 'Gender'])['Salary'].agg(['min', 'max']))

                     min    max
Department Gender
HR         F       45000  45000
           M       40000  40000
IT         F       60000  60000
           M       50000  50000
Sales      F       50000  50000
           M       55000  55000

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [147]:
# a = 

a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [148]:

print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[us]', length=457, freq='D')

What is the len of a?

In [149]:

print(len(a))

457

What is the type of a?

In [150]:

print(type(a))

<class 'pandas.DatetimeIndex'>